"use client";
import { useMemo, useState } from "react";
type GateName="H"|"X"|"Y"|"Z"|"S"|"T"; type Gate={name:GateName;qubit:number}; type C={r:number;i:number};
const info:Record<GateName,[string,string,string]>={H:["Hadamard","1/√2 [[1,1],[1,−1]]","Δημιουργεί υπέρθεση"],X:["Pauli-X","[[0,1],[1,0]]","Quantum NOT"],Y:["Pauli-Y","[[0,−i],[i,0]]","Περιστροφή γύρω από Y"],Z:["Pauli-Z","[[1,0],[0,−1]]","Αλλαγή φάσης"],S:["S gate","[[1,0],[0,i]]","Φάση π/2"],T:["T gate","[[1,0],[0,eⁱπ⁄⁴]]","Φάση π/4"]};
const z={r:0,i:0},o={r:1,i:0},h=Math.SQRT1_2;
const matrices:Record<GateName,C[][]>={H:[[{r:h,i:0},{r:h,i:0}],[{r:h,i:0},{r:-h,i:0}]],X:[[z,o],[o,z]],Y:[[z,{r:0,i:-1}],[{r:0,i:1},z]],Z:[[o,z],[z,{r:-1,i:0}]],S:[[o,z],[z,{r:0,i:1}]],T:[[o,z],[z,{r:h,i:h}]]};
const mul=(a:C,b:C)=>({r:a.r*b.r-a.i*b.i,i:a.r*b.i+a.i*b.r}); const add=(a:C,b:C)=>({r:a.r+b.r,i:a.i+b.i}); const fmt=(n:number)=>Math.abs(n)<.0005?"0":n.toFixed(3).replace(/0+$/,"").replace(/\.$/,"");
function simulate(gates:Gate[]){let s:C[]=Array.from({length:8},(_,i)=>({r:i?0:1,i:0}));gates.forEach(g=>{const m=matrices[g.name],bit=1<<(2-g.qubit),n=s.map(c=>({...c}));for(let i=0;i<8;i++){if(i&bit)continue;const j=i|bit;n[i]=add(mul(m[0][0],s[i]),mul(m[0][1],s[j]));n[j]=add(mul(m[1][0],s[i]),mul(m[1][1],s[j]))}s=n});return s}
function vector(s:C[],q:number){const bit=1<<(2-q);let x=0,y=0,zv=0;for(let i=0;i<8;i++){const p=s[i].r**2+s[i].i**2;zv+=(i&bit)?-p:p;if(!(i&bit)){const j=i|bit,c=mul(s[i],{r:s[j].r,i:-s[j].i});x+=2*c.r;y+=2*c.i}}return{x,y,z:zv}}
const presets:Record<string,Gate[]>={"Grover · 2 qubits":[{name:"H",qubit:0},{name:"H",qubit:1},{name:"Z",qubit:1},{name:"H",qubit:0}],"Superposition":[{name:"H",qubit:0}],"Phase kickback":[{name:"H",qubit:0},{name:"T",qubit:0},{name:"H",qubit:0}]};
export default function Home(){const[gates,setGates]=useState<Gate[]>([{name:"H",qubit:0},{name:"T",qubit:0},{name:"X",qubit:1}]);const[q,setQ]=useState(0);const[choice,setChoice]=useState<GateName>("H");const[shots,setShots]=useState(1024);const[counts,setCounts]=useState<Record<string,number>|null>(null);const[tab,setTab]=useState<"Qiskit"|"Cirq"|"Q#">("Qiskit");const state=useMemo(()=>simulate(gates),[gates]),v=useMemo(()=>vector(state,q),[state,q]);const states=state.map((c,i)=>({key:i.toString(2).padStart(3,"0"),p:c.r**2+c.i**2,c})).filter(a=>a.p>.0001);
const run=()=>{const ps=state.map(c=>c.r**2+c.i**2),out:Record<string,number>={};for(let n=0;n<shots;n++){let r=Math.random(),i=0;while(r>ps[i]&&i<7)r-=ps[i++];const k=i.toString(2).padStart(3,"0");out[k]=(out[k]||0)+1}setCounts(out)};
const code=tab==="Qiskit"?`from qiskit import QuantumCircuit\n\nqc = QuantumCircuit(3, 3)\n${gates.map(g=>`qc.${g.name.toLowerCase()}(${g.qubit})`).join("\n")}\nqc.measure(range(3), range(3))`:tab==="Cirq"?`import cirq\n\nq = cirq.LineQubit.range(3)\ncircuit = cirq.Circuit(\n${gates.map(g=>`    cirq.${g.name}(q[${g.qubit}]),`).join("\n")}\n    cirq.measure(*q, key='result')\n)`:`operation Main() : Result[] {\n    use q = Qubit[3];\n${gates.map(g=>`    ${g.name}(q[${g.qubit}]);`).join("\n")}\n    return MResetEachZ(q);\n}`;
return <main><header className="topbar"><a className="brand" href="#"><span className="logo">Q</span>quantoom</a><nav><a href="#lab">Playground</a><a href="#learn">Μαθήματα</a><a href="#algorithms">Αλγόριθμοι</a><a href="#code">Code Lab</a></nav><span className="badge">MVP · LOCAL SIMULATOR</span></header>
<section className="intro"><div><p className="eyebrow">QUANTUM LEARNING, VISUALIZED</p><h1>Δες το qubit.<br/><em>Χτίσε το κύκλωμα.</em></h1></div><p>Ένα διαδραστικό εργαστήριο κβαντικής υπολογιστικής. Πρόσθεσε πύλες, παρατήρησε τη σφαίρα Bloch και μέτρησε το κύκλωμά σου — χωρίς εγκατάσταση.</p></section>
<section id="lab" className="workspace"><div className="workspaceHead"><div><span className="dot"/> LIVE PLAYGROUND</div><button onClick={()=>{setGates([]);setCounts(null)}}>↺ Reset circuit</button></div><div className="labGrid"><aside className="gatePanel"><Title a="QUANTUM GATES" b="6"/><div className="gateGrid">{(Object.keys(info) as GateName[]).map(n=><button key={n} className={`gate ${choice===n?"active":""}`} onClick={()=>setChoice(n)}><b>{n}</b><span>{info[n][0]}</span></button>)}</div><div className="gateInfo"><b>{info[choice][0]}</b><small>{info[choice][2]}</small><code>{info[choice][1]}</code></div></aside>
<div className="circuitPanel"><Title a="CIRCUIT BUILDER" b="διάλεξε πύλη → πάτησε +"/><div className="circuit">{[0,1,2].map(n=><div className="wire" key={n}><button className={`qlabel ${q===n?"selected":""}`} onClick={()=>setQ(n)}>q{n}</button><span>|0⟩</span><div className="line"/>{gates.map((g,i)=>g.qubit===n?<button aria-label={`Αφαίρεση ${g.name}`} className="placed" style={{left:80+i*58}} key={i} onClick={()=>setGates(gates.filter((_,j)=>j!==i))}>{g.name}</button>:null)}<button className="addGate" onClick={()=>{setGates([...gates,{name:choice,qubit:n}]);setCounts(null)}}>+</button><span className="meter">⌁</span></div>)}</div><div className="state"><span>STATE VECTOR</span><code>{states.map(a=>`${fmt(a.c.r)}${a.c.i>=0?"+":""}${fmt(a.c.i)}i |${a.key}⟩`).join("  +  ")}</code></div></div>
<aside className="blochPanel"><Title a="BLOCH SPHERE" b={`q${q}`}/><svg className="bloch" viewBox="0 0 300 300" role="img" aria-label={`Bloch vector x ${fmt(v.x)}, y ${fmt(v.y)}, z ${fmt(v.z)}`}><defs><radialGradient id="orb"><stop offset="0" stopColor="#152633"/><stop offset="1" stopColor="#081015"/></radialGradient><marker id="arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5 0 7Z" fill="#b9ff4b"/></marker></defs><circle cx="150" cy="150" r="100" fill="url(#orb)" stroke="#46606a"/><ellipse cx="150" cy="150" rx="100" ry="27" fill="none" stroke="#334b55" strokeDasharray="4 5"/><ellipse cx="150" cy="150" rx="35" ry="100" fill="none" stroke="#263d47"/><path d="M35 150H265M150 35V265" stroke="#46606a"/><text x="267" y="154">x</text><text x="154" y="32">|0⟩</text><text x="154" y="282">|1⟩</text><line x1="150" y1="150" x2={150+v.x*78} y2={150-v.z*92+v.y*26} stroke="#b9ff4b" strokeWidth="4" markerEnd="url(#arrow)"/><circle cx={150+v.x*78} cy={150-v.z*92+v.y*26} r="6" fill="#e3ffb9"/></svg><div className="coords"><span>x <b>{fmt(v.x)}</b></span><span>y <b>{fmt(v.y)}</b></span><span>z <b>{fmt(v.z)}</b></span></div><div className="equation">|ψ⟩ = cos(θ/2)|0⟩ + e<sup>iφ</sup> sin(θ/2)|1⟩</div></aside></div></section>
<section className="lower"><div className="measure"><Label text="MEASUREMENT LAB"/><h2>Τρέξε το πείραμα</h2><p>Εκτέλεσε το κύκλωμα πολλές φορές και δες την κατανομή πιθανοτήτων.</p><div className="runRow"><label>Shots<select value={shots} onChange={e=>setShots(+e.target.value)}>{[100,512,1024,4096].map(n=><option key={n}>{n}</option>)}</select></label><button className="run" onClick={run}>▶ Run simulation</button></div><div>{(counts?Object.entries(counts).sort():states.map(a=>[a.key,Math.round(a.p*shots)] as [string,number])).map(([k,n])=><div className="barRow" key={k}><code>|{k}⟩</code><div className="track"><div className="bar" style={{width:`${Math.max(1,+n/shots*100)}%`}}/></div><b>{n}</b><span>{(+n/shots*100).toFixed(1)}%</span></div>)}</div></div>
<div id="code" className="codePanel"><Label text="MULTI-FRAMEWORK CODE LAB"/><h2>Από το visual στο code</h2><div className="tabs">{(["Qiskit","Cirq","Q#"] as const).map(t=><button className={tab===t?"active":""} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><pre><span>main.{tab==="Q#"?"qs":"py"}</span><code>{code}</code></pre></div></section>
<section id="algorithms" className="algorithms"><div><Label text="ALGORITHM EXPLORER"/><h2>Μάθε τους αλγόριθμους<br/>βήμα προς βήμα.</h2></div><div className="algorithmList">{Object.entries(presets).map(([name,p],i)=><button key={name} onClick={()=>{setGates(p);setCounts(null);document.getElementById("lab")?.scrollIntoView({behavior:"smooth"})}}><span>0{i+1}</span><div><b>{name}</b><small>{i===0?"Αναζήτηση σε μη ταξινομημένα δεδομένα":i===1?"Η βάση της κβαντικής παραλληλίας":"Κατανόησε τη σχετική φάση"}</small></div><strong>Load →</strong></button>)}</div></section>
<section id="learn" className="roadmap"><Label text="MVP LEARNING PATH"/><h2>Από το |0⟩ στο πρώτο σου κύκλωμα</h2><div className="steps">{[["01","Qubits & Υπέρθεση","State vectors, πιθανότητες και μέτρηση"],["02","Πύλες & Bloch Sphere","X, Y, Z, H και phase gates"],["03","Quantum Circuits","Σύνθεση πυλών και πειράματα"],["04","Algorithms","Grover, Deutsch–Jozsa και Shor overview"]].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section><footer><div className="brand"><span className="logo">Q</span>quantoom</div><p>Quantum computing, made tangible.</p><span>Built for curious minds · MVP 2026</span></footer></main>}
function Title({a,b}:{a:string;b:string}){return <div className="panelTitle"><span>{a}</span><small>{b}</small></div>} function Label({text}:{text:string}){return <p className="eyebrow">{text}</p>}
