"use client";
import {PointerEvent,useEffect,useMemo,useState} from "react";
import {blochVector,format,gateCatalog,generateCode,GateName,measure,Operation,parseCode,presets,probability,simulate} from "@/lib/quantum";
type Framework="Qiskit"|"Cirq"|"Q#";
const uid=()=>crypto.randomUUID();
const makePreset=(name:string)=>presets[name].ops.map(o=>({...o,id:uid()}));

export default function Home(){
  const[qubits,setQubits]=useState(3),[ops,setOps]=useState<Operation[]>(()=>makePreset("Bell state")),[gate,setGate]=useState<GateName>("H");
  const[targets,setTargets]=useState([0,1,2]),[angle,setAngle]=useState(Math.PI/2),[activeQubit,setActiveQubit]=useState(0);
  const[shots,setShots]=useState(1024),[counts,setCounts]=useState<Record<string,number>|null>(null),[framework,setFramework]=useState<Framework>("Qiskit");
  const[code,setCode]=useState(""),[codeDirty,setCodeDirty]=useState(false),[message,setMessage]=useState("Circuit ready"),[step,setStep]=useState<number|null>(null);
  const appliedOps=step===null?ops:ops.slice(0,step),state=useMemo(()=>simulate(appliedOps,qubits),[appliedOps,qubits]);
  const bloch=useMemo(()=>blochVector(state,activeQubit,qubits),[state,activeQubit,qubits]);
  const generated=useMemo(()=>generateCode(ops,qubits,framework),[ops,qubits,framework]);
  useEffect(()=>{if(!codeDirty)setCode(generated)},[generated,codeDirty]);
  useEffect(()=>{setTargets(t=>t.map((v,i)=>Math.min(v,qubits-1)));setActiveQubit(q=>Math.min(q,qubits-1));setCounts(null)},[qubits]);
  const catalog=Object.keys(gateCatalog) as GateName[],arity=gateCatalog[gate].arity;
  const addGate=()=>{const chosen=targets.slice(0,arity);if(new Set(chosen).size!==chosen.length){setMessage("Choose different qubits for every gate role");return}setOps([...ops,{id:uid(),name:gate,targets:chosen,angle:["RX","RY","RZ"].includes(gate)?angle:undefined}]);setCounts(null);setStep(null);setMessage(`${gateCatalog[gate].label} added`)};
  const loadPreset=(name:string)=>{setQubits(presets[name].qubits);setOps(makePreset(name));setCounts(null);setStep(null);setMessage(`${name} loaded`)};
  const run=()=>{setCounts(measure(state,qubits,shots));setStep(null);setMessage(`${shots.toLocaleString()} shots completed`)};
  const applyCode=()=>{const parsed=parseCode(code,framework);if(!parsed.length){setMessage("No supported gate instructions found");return}const max=Math.max(...parsed.flatMap(o=>o.targets));setQubits(Math.max(1,Math.min(5,max+1)));setOps(parsed);setCounts(null);setCodeDirty(false);setMessage(`${parsed.length} operations imported from ${framework}`)};
  const download=()=>{const ext=framework==="Q#"?"qs":"py",blob=new Blob([code],{type:"text/plain"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`quantoom-circuit.${ext}`;a.click();URL.revokeObjectURL(url)};
  const rows=state.map((c,i)=>({key:i.toString(2).padStart(qubits,"0"),p:probability(c),c})).filter(v=>v.p>.00005).sort((a,b)=>b.p-a.p);
  return <main><header className="topbar"><a className="brand" href="#workbench"><span className="logo">Q</span><span>quantoom</span><small>LAB</small></a><nav><a href="#workbench">Workbench</a><a href="#code-lab">Code</a><a href="#experiments">Experiments</a><a href="#guide">Guide</a></nav><div className="status"><span/> Simulator online</div></header>

  <section id="workbench" className="workbench"><div className="wbTop"><div><p>QUANTUM WORKBENCH</p><h1>Untitled circuit <span>• {qubits} qubits • {ops.length} operations</span></h1></div><div className="topActions"><label>Qubits<select value={qubits} onChange={e=>{setQubits(+e.target.value);setOps([])}}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><button onClick={()=>{setOps([]);setCounts(null);setStep(null)}}>Clear</button><button className="primary" onClick={run}>▶ Run circuit</button></div></div>
  <div className="workspaceGrid"><aside className="palette"><PanelTitle title="GATE LIBRARY" value={`${catalog.length} gates`}/><div className="gateGroups">{["Single-qubit","Phase","Rotation","Controlled","Multi-qubit"].map(group=><div key={group}><h3>{group}</h3><div className="gateButtons">{catalog.filter(g=>gateCatalog[g].group===group).map(g=><button key={g} className={gate===g?"selected":""} onClick={()=>setGate(g)}><b>{g}</b><span>{gateCatalog[g].label}</span></button>)}</div></div>)}</div><div className="gateDetail"><strong>{gateCatalog[gate].label}</strong><p>{gateCatalog[gate].description}</p><code>{gateCatalog[gate].matrix}</code></div></aside>
  <section className="circuitArea"><div className="circuitToolbar"><PanelTitle title="CIRCUIT" value={step===null?"Final state":`Step ${step}/${ops.length}`}/><div className="stepper"><button onClick={()=>setStep(s=>s===null?Math.max(0,ops.length-1):Math.max(0,s-1))}>←</button><button onClick={()=>setStep(s=>s===null?0:Math.min(ops.length,s+1))}>{step===null?"Step through":"Next step"}</button><button onClick={()=>setStep(null)}>Final</button></div></div><Circuit qubits={qubits} ops={ops} activeStep={step} selectQubit={setActiveQubit} remove={id=>{setOps(ops.filter(o=>o.id!==id));setCounts(null)}}/>
  <div className="composer"><div className="composerGate"><b>{gate}</b><span>{gateCatalog[gate].label}</span></div>{Array.from({length:arity},(_,i)=><label key={i}>{arity===1?"Qubit":i===arity-1?"Target":`Control ${i+1}`}<select value={targets[i]} onChange={e=>setTargets(t=>t.map((v,j)=>j===i?+e.target.value:v))}>{Array.from({length:qubits},(_,q)=><option key={q} value={q}>q{q}</option>)}</select></label>)}{["RX","RY","RZ"].includes(gate)&&<label>Angle<select value={angle} onChange={e=>setAngle(+e.target.value)}><option value={Math.PI/4}>π/4</option><option value={Math.PI/2}>π/2</option><option value={Math.PI}>π</option></select></label>}<button className="add" onClick={addGate}>＋ Add gate</button></div>
  <div className="stateVector"><div><PanelTitle title="STATE VECTOR" value={`${rows.length}/${2**qubits} non-zero`}/>{rows.slice(0,8).map(v=><div className="amplitude" key={v.key}><code>|{v.key}⟩</code><div><i style={{width:`${v.p*100}%`}}/></div><span>{(v.p*100).toFixed(2)}%</span><small>{format(v.c.r)} {v.c.i>=0?"+":"−"} {format(Math.abs(v.c.i))}i</small></div>)}</div></div></section>
  <aside className="inspector"><PanelTitle title="QUBIT INSPECTOR" value={`q${activeQubit}`}/><div className="qubitTabs">{Array.from({length:qubits},(_,q)=><button className={activeQubit===q?"active":""} onClick={()=>setActiveQubit(q)} key={q}>q{q}</button>)}</div><BlochSphere vector={bloch}/><div className="coordinates"><span><small>x</small><b>{format(bloch.x)}</b></span><span><small>y</small><b>{format(bloch.y)}</b></span><span><small>z</small><b>{format(bloch.z)}</b></span></div><div className="purity"><div><span>Bloch radius / purity</span><b>{(bloch.purity*100).toFixed(1)}%</b></div><div><i style={{width:`${bloch.purity*100}%`}}/></div><p>{bloch.purity<.999?"Mixed reduced state — this qubit is entangled with the register.":"Pure single-qubit state."}</p></div><div className="mathBlock"><span>STATE PARAMETRIZATION</span><p>|ψ⟩ = cos(θ/2)|0⟩ + e<sup>iφ</sup>sin(θ/2)|1⟩</p><code>θ = {format(bloch.theta)} rad · φ = {format(bloch.phi)} rad</code></div></aside></div></section>

  <section id="code-lab" className="codeLab"><div className="sectionHead"><div><p>ROUND-TRIP CODE LAB</p><h2>Circuit and code stay in sync.</h2></div><p>Edit supported gate calls and import them back into the visual circuit. Export runnable code for your preferred framework.</p></div><div className="codeGrid"><div className="editor"><div className="editorTop"><div className="tabs">{(["Qiskit","Cirq","Q#"] as Framework[]).map(f=><button className={framework===f?"active":""} key={f} onClick={()=>{setFramework(f);setCodeDirty(false)}}>{f}</button>)}</div><div><button onClick={()=>{navigator.clipboard.writeText(code);setMessage("Code copied")}}>Copy</button><button onClick={download}>↓ Download</button></div></div><textarea spellCheck={false} value={code} onChange={e=>{setCode(e.target.value);setCodeDirty(true)}}/><div className="editorFoot"><span>{codeDirty?"Edited code — apply to update circuit":"Synced with visual circuit"}</span><button className="primary" onClick={applyCode}>Apply code → circuit</button></div></div><div className="runner"><PanelTitle title="LOCAL STATEVECTOR RUNNER" value={message}/><div className="runnerControls"><label>Shots<select value={shots} onChange={e=>setShots(+e.target.value)}>{[100,512,1024,4096,10000].map(n=><option key={n}>{n}</option>)}</select></label><button className="primary" onClick={run}>▶ Simulate & measure</button></div><div className="histogram">{(counts?Object.entries(counts).sort((a,b)=>b[1]-a[1]):rows.map(v=>[v.key,Math.round(v.p*shots)] as [string,number])).slice(0,10).map(([key,val])=><div className="histRow" key={key}><code>|{key}⟩</code><div><i style={{width:`${Math.max(1,val/shots*100)}%`}}/></div><b>{val}</b><span>{(val/shots*100).toFixed(1)}%</span></div>)}</div></div></div></section>

  <section id="experiments" className="experiments"><div className="sectionHead"><div><p>EXPERIMENT LIBRARY</p><h2>Research-grade concepts,<br/>ready to inspect.</h2></div><p>Load a canonical experiment, step through every operation, inspect reduced qubit states and compare predicted probabilities with sampled results.</p></div><div className="presetGrid">{Object.entries(presets).map(([name,p],i)=><button key={name} onClick={()=>{loadPreset(name);document.getElementById("workbench")?.scrollIntoView({behavior:"smooth"})}}><span>0{i+1}</span><div><b>{name}</b><p>{p.description}</p><small>{p.qubits} qubits · {p.ops.length} operations</small></div><strong>Load ↗</strong></button>)}</div></section>

  <section id="guide" className="guide"><div><p>WORKFLOW</p><h2>From idea to evidence.</h2></div><ol><li><span>01</span><b>Compose</b><p>Select a gate, assign its control/target qubits and add it to the circuit.</p></li><li><span>02</span><b>Inspect</b><p>Select a qubit and rotate its Bloch sphere. Step through the circuit to see state evolution.</p></li><li><span>03</span><b>Translate</b><p>Switch between Qiskit, Cirq and Q#. Edit code and apply supported instructions back to the circuit.</p></li><li><span>04</span><b>Validate</b><p>Choose shot count, simulate measurements and compare the histogram with exact state probabilities.</p></li><li><span>05</span><b>Export</b><p>Download the runnable source file for notebooks, research workflows or engineering review.</p></li></ol></section><footer><div className="brand"><span className="logo">Q</span><span>quantoom</span></div><p>Quantum circuits made observable.</p><span>Local simulation · No data leaves your browser</span></footer></main>
}

function PanelTitle({title,value}:{title:string;value:string}){return <div className="panelTitle"><span>{title}</span><small>{value}</small></div>}
function Circuit({qubits,ops,activeStep,selectQubit,remove}:{qubits:number;ops:Operation[];activeStep:number|null;selectQubit:(q:number)=>void;remove:(id:string)=>void}){return <div className="circuit"><div className="circuitScroll"><div className="labels">{Array.from({length:qubits},(_,q)=><button key={q} onClick={()=>selectQubit(q)}><b>q{q}</b><span>|0⟩</span></button>)}</div><div className="columns">{ops.length===0&&<div className="emptyCircuit">Add a gate to begin</div>}{ops.map((op,index)=><div className={`opColumn ${activeStep!==null&&index>=activeStep?"future":""}`} key={op.id} style={{gridTemplateRows:`repeat(${qubits},58px)`}}>{Array.from({length:qubits},(_,q)=><div className="wireCell" key={q}>{op.targets.includes(q)&&<GateMark op={op} index={op.targets.indexOf(q)} remove={()=>remove(op.id)}/>}</div>)}{op.targets.length>1&&<i className="connector" style={{top:29+Math.min(...op.targets)*58,height:(Math.max(...op.targets)-Math.min(...op.targets))*58}}/>}<small>{index+1}</small></div>)}</div></div></div>}
function GateMark({op,index,remove}:{op:Operation;index:number;remove:()=>void}){const controlled=["CX","CZ","CCX"].includes(op.name),isControl=controlled&&index<op.targets.length-1,label=op.name==="CX"&&index===1?"⊕":op.name==="CCX"&&index===2?"⊕":op.name==="SWAP"?"×":isControl?"•":op.name;return <button className={`gateMark ${isControl?"control":""}`} onClick={remove} aria-label={`Remove ${op.name}`}>{label}</button>}

function BlochSphere({vector}:{vector:{x:number;y:number;z:number;purity:number}}){const[yaw,setYaw]=useState(-.55),[pitch,setPitch]=useState(.25),[drag,setDrag]=useState<{x:number;y:number;sy:number;sp:number}|null>(null);const project=(x:number,y:number,z:number)=>{const cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),x1=x*cy-z*sy,z1=x*sy+z*cy,y1=y*cp-z1*sp,z2=y*sp+z1*cp;return{x:150+x1*102,y:150-y1*102,z:z2}};const p=project(vector.x,vector.y,vector.z),axis=(x:number,y:number,z:number)=>project(x,y,z);const lines=[];for(let lat=-60;lat<=60;lat+=30){const points=[];const rad=lat*Math.PI/180;for(let a=0;a<=360;a+=8)points.push(project(Math.cos(rad)*Math.cos(a*Math.PI/180),Math.cos(rad)*Math.sin(a*Math.PI/180),Math.sin(rad)));lines.push(points)}for(let lon=0;lon<180;lon+=30){const points=[];const rad=lon*Math.PI/180;for(let a=-90;a<=90;a+=6)points.push(project(Math.cos(a*Math.PI/180)*Math.cos(rad),Math.cos(a*Math.PI/180)*Math.sin(rad),Math.sin(a*Math.PI/180)));lines.push(points)}const path=(pts:{x:number;y:number}[])=>pts.map((v,i)=>`${i?"L":"M"}${v.x.toFixed(1)} ${v.y.toFixed(1)}`).join(" ");const down=(e:PointerEvent<SVGSVGElement>)=>{e.currentTarget.setPointerCapture(e.pointerId);setDrag({x:e.clientX,y:e.clientY,sy:yaw,sp:pitch})};const move=(e:PointerEvent<SVGSVGElement>)=>{if(drag){setYaw(drag.sy+(e.clientX-drag.x)/140);setPitch(Math.max(-1.2,Math.min(1.2,drag.sp+(e.clientY-drag.y)/140)))}};return <div className="sphereWrap"><svg viewBox="0 0 300 300" onPointerDown={down} onPointerMove={move} onPointerUp={()=>setDrag(null)} role="img" aria-label="Interactive three-dimensional Bloch sphere. Drag to rotate."><defs><radialGradient id="sphere" cx="34%" cy="27%"><stop offset="0" stopColor="#284a47" stopOpacity=".95"/><stop offset=".46" stopColor="#102927" stopOpacity=".9"/><stop offset="1" stopColor="#06100f" stopOpacity=".98"/></radialGradient><radialGradient id="glow"><stop offset="0" stopColor="#dfff9f"/><stop offset="1" stopColor="#9cfb45"/></radialGradient><filter id="shadow"><feGaussianBlur stdDeviation="9"/></filter><clipPath id="clip"><circle cx="150" cy="150" r="102"/></clipPath><marker id="vecArrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5 0 7Z" fill="#b9ff4b"/></marker></defs><ellipse cx="150" cy="266" rx="76" ry="12" fill="#000" opacity=".55" filter="url(#shadow)"/><circle cx="150" cy="150" r="102" fill="url(#sphere)" stroke="#5a7773" strokeWidth="1.2"/>
<g clipPath="url(#clip)" opacity=".5">{lines.map((l,i)=><path d={path(l)} key={i} fill="none" stroke={i<5?"#56706d":"#3d5c58"} strokeWidth=".7"/>)}</g>{[[1,0,0,"x"],[0,1,0,"y"],[0,0,1,"|0⟩"],[0,0,-1,"|1⟩"]] .map(([x,y,z,label])=>{const a=axis(x as number,y as number,z as number);return <g key={label as string}><line x1="150" y1="150" x2={a.x} y2={a.y} stroke="#78908d" strokeWidth=".8" strokeDasharray="3 4"/><text x={a.x+(a.x>150?6:-16)} y={a.y+(a.y>150?14:-5)}>{label}</text></g>})}<line x1="150" y1="150" x2={p.x} y2={p.y} stroke="#b9ff4b" strokeWidth="4" markerEnd="url(#vecArrow)" className="vector"/><circle cx={p.x} cy={p.y} r="7" fill="url(#glow)"/><circle cx="150" cy="150" r="3" fill="#cfe3df"/></svg><span>Drag to rotate</span></div>}
